### ISSUE TITLE
AttributeError: module 'cloudinit.util' has no attribute 'yaml_dumps'

### ISSUE THREAD

**Issue by jeh0s** [zalando-stups/taupage#594]
`ZalandoAMIConfigPartHandler` handler cannot save user-data of the instance of ec2 as '/meta/taupage.yaml'.

```
2020-04-02 09:03:40,900 - util.py[WARNING]: Failed calling handler ZalandoAMIConfigPartHandler: [['text/x-taupage-ami-config']] (text/x-taupage-ami-config, part-001, 2) with frequency once-per-instance
2020-04-02 09:03:40,900 - util.py[DEBUG]: Failed calling handler ZalandoAMIConfigPartHandler: [['text/x-taupage-ami-config']] (text/x-taupage-ami-config, part-001, 2) with frequency once-per-instance
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/handlers/__init__.py", line 109, in run_part
    payload, frequency)
  File "/usr/lib/python3/dist-packages/cloudinit/handlers/zalando_ami_config.py", line 46, in handle_part
    config_yaml = util.yaml_dumps(config_merged)
AttributeError: module 'cloudinit.util' has no attribute 'yaml_dumps'
```

Therefore, an error occurs as config cannot be processed while processing 'init.d/02-register-td-agent.py'.

```
<13>Apr  2 07:13:36 taupage-init: Traceback (most recent call last):
<13>Apr  2 07:13:36 taupage-init:   File "././init.d/02-register-td-agent.py", line 184, in <module>
<13>Apr  2 07:13:36 taupage-init:     update_configuration_from_template(s3_default)
<13>Apr  2 07:13:36 taupage-init:   File "././init.d/02-register-td-agent.py", line 60, in update_configuration_from_template
<13>Apr  2 07:13:36 taupage-init:     image = config.get('source').split(':', 1)[0]
<13>Apr  2 07:13:36 taupage-init: AttributeError: 'NoneType' object has no attribute 'split'
<13>Apr  2 07:13:36 taupage-init: ERROR: ./init.d/02-register-td-agent.py did not successfully finish
```

**Comment by jeh0s** [comment]
```
ubuntu@ip-172-31-37-100:/var/log⟫ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

ubuntu@ip-172-31-37-100:/var/log⟫ dpkg -l | grep cloud-init
ii  cloud-init                       19.4-33-gbb4131a2-0ubuntu1~16.04.1         all          Init scripts for cloud instances
ii  cloud-initramfs-copymods         0.27ubuntu1.6                              all          copy initramfs modules into root filesystem for later use
ii  cloud-initramfs-dyn-netconf      0.27ubuntu1.6                              all          write a network interface file in /run for BOOTIF
```


SEE ALSO:

**Fix usages of yaml, and move yaml_dump to safeyaml.dumps.** - https://github.com/canonical/cloud-init/commit/5bec6b0e2a2ce5fd03bb04f441536fc130e67997
*ubuntu/20.1-10-g71af48df-0ubuntu2*

**Comment by aermakov-zalando** [comment]
This repository is no longer supported, so we won't be able to offer any help. Sorry about not communicating it properly.

**Comment by jeh0s** [comment]
Oh, I see. I try to using spilo for high availability setup of PostgreSQL. So I want to use taupage. If all of these projects are deprecated, is there any alternative? @aermakov-zalando

**Comment by aermakov-zalando** [comment]
I see! I don't think Spilo requires Taupage, so just run it on any AMI that has Docker. If that doesn't work, please raise these questions with the Spilo maintainers, they'd be able to provide better answers.
