### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#72]
Jun 15 07:55:12 ip-172-31-12-207 taupage-init: Traceback (most recent call last):
Jun 15 07:55:12 ip-172-31-12-207 taupage-init:   File "/opt/taupage/runtime/Docker.py", line 297, in <module>
Jun 15 07:55:12 ip-172-31-12-207 taupage-init:     main(args)
Jun 15 07:55:12 ip-172-31-12-207 taupage-init:   File "/opt/taupage/runtime/Docker.py", line 278, in main
Jun 15 07:55:12 ip-172-31-12-207 taupage-init:     cmd += list(f(config))
Jun 15 07:55:12 ip-172-31-12-207 taupage-init:   File "/opt/taupage/runtime/Docker.py", line 132, in get_port_options
Jun 15 07:55:12 ip-172-31-12-207 taupage-init:     if '/' in host_port:
Jun 15 07:55:12 ip-172-31-12-207 taupage-init: TypeError: argument of type 'int' is not iterable

**Comment by hjacobs** [comment]
Introduced by @CyberDem0n with latest PR regarding UDP support

**Comment by hjacobs** [comment]
fixed
