### ISSUE TITLE
mdadm 10-prepare-disks.py fails 

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#73]
The "prepare-disks" script seems to fail (sometimes) when running mdadm (to build a raid with two devices):

```
Jun 15 08:10:27 ip-172-31-15-220 kernel: [   23.830888] blkfront: xvdf: barrier or flush: disabled; persistent grants: disabled; indirect descriptors: enabled;
Jun 15 08:10:27 ip-172-31-15-220 kernel: [   23.834668]  xvdf: unknown partition table
Jun 15 08:10:29 ip-172-31-15-220 kernel: [   25.728675] blkfront: xvdi: barrier or flush: disabled; persistent grants: disabled; indirect descriptors: enabled;
Jun 15 08:10:29 ip-172-31-15-220 kernel: [   25.733076]  xvdi: unknown partition table
Jun 15 08:10:31 ip-172-31-15-220 kernel: [   28.031018] blkfront: xvdg: barrier or flush: disabled; persistent grants: disabled; indirect descriptors: enabled;
Jun 15 08:10:31 ip-172-31-15-220 kernel: [   28.035338]  xvdg: unknown partition table
Jun 15 08:10:29 ip-172-31-15-220 taupage-init: message repeated 2 times: [ Waiting for /dev/xvdh to stabilize]
Jun 15 08:10:32 ip-172-31-15-220 taupage-init: mdadm: Cannot find /dev/xvdh: No such file or directory
Jun 15 08:10:32 ip-172-31-15-220 ntpd[1534]: ntpd exiting on signal 15
Jun 15 08:10:32 ip-172-31-15-220 taupage-init: Traceback (most recent call last):
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:   File "./init.d/10-prepare-disks.py", line 237, in <module>
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:     main()
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:   File "./init.d/10-prepare-disks.py", line 230, in main
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:     handle_volumes(args, config)
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:   File "./init.d/10-prepare-disks.py", line 206, in handle_volumes
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:     handle_raid_volumes(volumes.get("raid"))
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:   File "./init.d/10-prepare-disks.py", line 193, in handle_raid_volumes
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:     create_raid_device(raid_device, raid_config)
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:   File "./init.d/10-prepare-disks.py", line 184, in create_raid_device
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:     subprocess.check_call(call)
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:   File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
Jun 15 08:10:32 ip-172-31-15-220 taupage-init:     raise CalledProcessError(retcode, cmd)
Jun 15 08:10:32 ip-172-31-15-220 taupage-init: subprocess.CalledProcessError: Command '['mdadm', '--build', '/dev/md/sampleraid1', '--level=1', '--raid-devices=2', '/dev/xvdh', '/dev/xvdi']' returned non-zero exit status 1
Jun 15 08:10:32 ip-172-31-15-220 taupage-init: Failed to start 10-prepare-disks.py
Jun 15 08:10:33 ip-172-31-15-220 kernel: [   30.036629] blkfront: xvdh: barrier or flush: disabled; persistent grants: disabled; indirect descriptors: enabled;
Jun 15 08:10:33 ip-172-31-15-220 kernel: [   30.041170]  xvdh: unknown partition table

**Comment by femueller** [comment]
I can not reproduce this issue anymore.
Apparently the configuration was just wrong. But right now the build process and manual raid configuration just works.

**Comment by femueller** [comment]
Apparently this issue still exists/appeared again.
